### ISSUE TITLE
Grunt build failing

### ISSUE THREAD

**Issue by dylanb** [jquery/css-chassis#107]
I have cloned and tried to build the latest master branch with the following result:

```
Running "svgmin:dist" (svgmin) task
✔ icons/svg-source/circle.svg (saved 280 B 74%)
✔ icons/svg-source/square.svg (saved 297 B 77%)
✔ icons/svg-source/triangle.svg (saved 300 B 73%)
Total saved: 877 B

Running "svgstore:defaults" (svgstore) task
File icons/icons.svg created.

Running "sass:dist" (sass) task
Warning: /Users/dylanbarrell/private/css-chassis/scss/atoms/typography/typography:8: file to import not found or unreadable: "dist/chassis"
Current dir: /Users/dylanbarrell/private/css-chassis/scss/atoms/typography/
 Use --force to continue.
```

I am pretty sure this used to work - any ideas?

**Comment by sfrisk** [comment]
Hey, we're working on a fix for that, although right now if you create a "dist" folder in the home css-chassis directory, you should be able to build.

**Comment by dylanb** [comment]
There must be slightly more to it than that because I do have a dist directory and when I added a "chassis" file in that directory, I get:

```
Running "sass:dist" (sass) task
Warning: /Users/dylanbarrell/private/css-chassis/scss/atoms/typography/typography:13: unbound variable $normal
 Use --force to continue.
```

**Comment by sfrisk** [comment]
I'll look into it.  I know @arschmitz's PR #104 is supposed to be addressing these issues, I'll see if I can get the build working this evening.

**Comment by dylanb** [comment]
PR #104 did fix my issue

**Comment by dylanb** [comment]
Now I get

```
Warning: Task "perfjankie" not found. Use --force to continue.
```

Booohoooohoooo!!
^=== me crying like a baby

**Comment by sfrisk** [comment]
Hey @dylanb we're on it, it will be the top priority item in the meeting today.

**Comment by sfrisk** [comment]
Was this doing `grunt build` or `grunt perf` ?

**Comment by dylanb** [comment]
thanks - I actually found that I did not need to get the perf stuff to work in order to integrate some accessibility testing. I will be submitting a PR for review on approach.

**Comment by dylanb** [comment]
Not sure if this helps, but here is how I got around the problem:

1) Include the "buildVariables" task dependency from #104 
2) `mkdir dist` then `touch dist/chassis`
3) `grunt build` this creates a chassis.scss file
4) `rm dist/chassis`
