### ISSUE TITLE
Re-evaluate Chassis Meeting Time

### ISSUE THREAD

**Issue by sfrisk** [jquery/css-chassis#122]
With new jobs of the contributing members, it would appear that the 1:00 Tuesday meeting time is no longer a great means of getting the team together for weekly meetings. Do we want to re-evaluate our meeting time, and perhaps vote on a time that works better for everyone?  If so, what days/times tend to work well for everyone?

**Comment by arschmitz** [comment]
Yeah sadly this time no longer works from me as i have a daily meeting from 12:30 - 1:15 eastern every day aside from that and other jquery meetings i'm "fairly" open.

Maybe a doodle like we did the first time would be best

**Comment by sfrisk** [comment]
@arschmitz @geekman-rohit @arthurvr Here is the meeting doodle: http://doodle.com/poll/npw7hx3kd3fke3a4

**Comment by arschmitz** [comment]
FYI 2-3 on Thursdays conflicts with jQuery Mobile meeting in same channel

**Comment by sfrisk** [comment]
Oops, I think I was looking at the wrong date. Updated it.

**Comment by arthurvr** [comment]
@sfrisk Done, thanks for the reminder.

**Comment by sfrisk** [comment]
Right now it is looking like Tuesday 2pm - 3pm (EST) is the one that works the best for most people. I'm going to leave the Doodle open the rest of the week just in case any other potential contributors are interested in joining in.

**Comment by sfrisk** [comment]
So it looks like Tuesday from 2pm - 3pm won out. Well do the first meeting at that time this week!

**Comment by arthurvr** [comment]
Don't forget to update the calendar on meetings.jquery.org :)

**Comment by sfrisk** [comment]
I think @dmethvin might have to be the one who does that. I lack the power.  However, I'll update our Contributing doc with the new time.

**Comment by kborchers** [comment]
I have updated the event. Can you check and make sure it is correct on your calendars in different time zones?

**Comment by sfrisk** [comment]
Looks good to me, but I'm Eastern.  @arthurvr ? @geekman-rohit ?

**Comment by arthurvr** [comment]
lgtm

**Comment by geekman-rohit** [comment]
@sfrisk  Looks Good to me too. I was travelling last night, hence couldn't make it.

**Comment by sfrisk** [comment]
jQuery Meetings has been updated as well as our contribute file, closing this issue.
