### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by arschmitz** [jquery/css-chassis#13]
Since we want this to be kind of like a pseudo standard I think we should create a mailing list for discussion.

**Comment by sfrisk** [comment]
Are we still going to do this?

**Comment by jzaefferer** [comment]
Creating Google Groups is pretty straight forward and low maintenance. Go for it!

**Comment by arschmitz** [comment]
Yeah i would say just go for it!

**Comment by arthurvr** [comment]
:+1: For sure!

**Comment by cvrebert** [comment]
> Creating Google Groups is pretty straight forward and low maintenance.

Well, it's not quite turnkey. You do need someone actively monitoring it for spam and moderating any spammers. If it gets overrun by spammers, Google will shut down the group.
Maybe consider [Librelist](http://librelist.com)?
(I'm kinda surprised the jQuery Foundation doesn't have a [mailman](http://www.gnu.org/software/mailman/) instance.)

**Comment by MichaelArestad** [comment]
I'm not sure why we would even need one. All discussion could easily take place here and on IRC.

**Comment by arschmitz** [comment]
This was intended to be a private not a public mailing list. We use them on some other projects and it works well for some things where non public discussion is needed

**Comment by sfrisk** [comment]
As discussed in the meeting today, I'll set up a private Google Group for us.

**Comment by sfrisk** [comment]
Google group can be found: https://groups.google.com/forum/?hl=en#!forum/css-chassis
