### ISSUE TITLE
Initial 'grunt build' aborting due to warnings

### ISSUE THREAD

**Issue by ryancharris** [jquery/css-chassis#152]
After forking and cloning to my local machine I ran `npm install`, which worked. However, `grunt build` is aborting due to a missing node module while running the variables task.

cc: #107 

![screen shot 2016-03-23 at 11 19 14 am](https://cloud.githubusercontent.com/assets/4997781/14005116/33d31b38-f136-11e5-816d-f1b0ddf556fd.png)

**Comment by sfrisk** [comment]
What version of Node are you using?

**Comment by ryancharris** [comment]
@sfrisk Node v5.9.0

![screen shot 2016-03-23 at 9 14 50 pm](https://cloud.githubusercontent.com/assets/4997781/14005722/5ca1011e-f13c-11e5-8ad8-21fc624e8157.png)

**Comment by ryancharris** [comment]
@sfrisk Upgraded to 5.9.1 and the build still fails

**Comment by sfrisk** [comment]
I think this might be fixed by a current PR, but let me double check.

ping @arschmitz

**Comment by arschmitz** [comment]
build for node 5.x is fixed by #154

**Comment by sfrisk** [comment]
Going to prioritize pulling in that PR for today's meeting

**Comment by sfrisk** [comment]
Hey, we've pulled in the code that should fix this problem.

**Comment by ryancharris** [comment]
@sfrisk Works on my end. Built without any errors.  👍 
![screen shot 2016-04-12 at 1 09 23 pm](https://cloud.githubusercontent.com/assets/4997781/14468925/1a700582-00b0-11e6-94a4-a1e659004bc8.png)
