### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by sfrisk** [jquery/css-chassis#16]
Assuming we want to cover typography along with form elements in the first release, the following items need to be considered:

What font do we want to use?  Do we want to allow for different fonts, and allow user to choose? Font color?

We need styling (font, font size, line-height, font-weight, etc) for most if not all of the following elements:

* Headers (`<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>`)
* Classes meant to mimic headers, but not semantically mean the header they're mimicking ( For example, a `.h1` class to use on an `<h2>` that someone wants to appear like an `<h1>`.
* Paragraphs (`<p>`)
* Inline text elements (`<mark>`, `<del>`, `<s>`, `<ins>`, `<u>`, `<small>`, `<strong>`, `<em>`, `<b>`, `<i>`)
* Lists (Ordered, Unordered, Definition)
* Block quotes? Addresses?

Also do we want any utility typography classes, for text alignment or text transformation?

**Comment by GreatDanton** [comment]
:+1:  for Source Sans Pro. When I was writing my site, I was searching for font that would look nice no matter at which size. So I was browsing around, looking for sites and marking the fonts that I like. I ended up with 5 fonts. Lato, Open Sans, Droid sans, Roboto, Source Sans Pro. After trying each of them I decided Source Sans Pro got the best word spacing.

Oh, and hi btw :)
