### ISSUE TITLE
normalize not being compiled in dist files.

### ISSUE THREAD

**Issue by nashvail** [jquery/css-chassis#168]
Grunt doesn't seem to be compiling normalize.scss file located at /external/normalize.css/normalize.scss in the distributable files. 
@arschmitz

**Comment by arschmitz** [comment]
@nashvail ok thanks ill take a look

**Comment by Slayslot** [comment]
@arschmitz Can I take a look at this?

**Comment by sfrisk** [comment]
There is a pull request open for this. You can help review it.

**Comment by rohmulan** [comment]
I forgot to add this. Fixed in 66e5b35
