### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by arschmitz** [jquery/css-chassis#27]
Now that we have a name we really need a logo.

@isaacdurazo you had expressed interest in helping do you think this is something you could tackle? It would be a huge help to be able to get things going!

**Comment by isaacdurazo** [comment]
Just FYI guys, I've started to brainstorm a little bit on this. Nothing to show yet but wanted to let you know that I've started working on this.

<3

**Comment by arschmitz** [comment]
@isaacdurazo Awesome thanks for the update! Can't wait!

**Comment by sfrisk** [comment]
Yay!! :+1:

**Comment by isaacdurazo** [comment]
Hey guys, I've been working on this for severals days now and here's a first option. 

I'm keeping it simple by taking the idea of the "chassis" and do something that evokes it a little bit.

![screen shot 2015-01-26 at 10 32 48 pm](https://cloud.githubusercontent.com/assets/1379244/5914042/568e0778-a5ab-11e4-80fc-4b1c5f454e14.png)

What do you think?

**Comment by sfrisk** [comment]
Ooooo.

I like the b/w version and the font, and the overall simplicity of the design. Not quite sure what I think of the logo with the green background, but I like the green with white background.

Overall I like the direction you're going with this though.

**Comment by arschmitz** [comment]
Overall I agree with sfrisk I like the font a lot and the logo. I like the first 2 more then the third also not sure on the green back. 

One comment I would make as far as evoking the idea of a chassis. I get the idea completely of the c being like the internal structure or "chassis". I guess to me though just due to common usage being generally one of 2 specific things ( a car frame or computer case ) it does not really evoke the idea of a chassis to me. That being said I would not necessarily change, to make it evoke that. I like the logo a lot and think it will work well in usage and like the simplicity. Just wanted to throw that out there. 

Nice work though really like it and the font a lot!

**Comment by isaacdurazo** [comment]
Thanks guys, I'm glad you liked it. I was thinking on the idea of the "chassis" more as a base/structure of something, so I didn't want to go to literal there.

Regarding colors, all these 3 are part of the same option. I forgot to mention that part (oops). We need to have the ability to use the logo in different scenarios, like on a white background or a color background, and also a monochrome version. 

You guys mentioned you liked the colors, would you be interested in seeing a few more options? I wanted to show what I had as the graphic before experimenting with colors, that's why I didn't posted other variations.

**Comment by sfrisk** [comment]
Ahhh, okay I understand.  I saw it as three different logos, rather than "this is some allowed use cases for this logo."

I definitely would be interested in seeing a few more color options.

**Comment by arschmitz** [comment]
@isaacdurazo Yeah i totally get where you were going ( and knew immediately ). So I think your concept was clear. I was only commenting about my own personal impressions of the word. Your interpretation is 100% accurate to the actual meaning of the word. 

As far as color, I knew what you were going for with the 3 variations, I was only thinking as you said maybe slightly different colors. The `darkslategray` on that green just does not pop well to me. Maybe even stick with same colors but for the green back go with white? I don't know ill leave that to you your the designer :-)

**Comment by arschmitz** [comment]
Something I noticed, I feel at least worth mentioning here, while not the same green for sure. The green here is at least semi similar to the jQuery Mobile green. http://brand.jquery.org/colors/#jquery-mobile-green. Don't think its close enough to be a big deal but thought I would mention.

**Comment by MichaelArestad** [comment]
The icon is pretty dang good and could be quite a bit of fun to animate (with CSS).

I'm not sure the typeface fits, though. The icon is very geometric with hard edges, uniform line weight, and sharp corners while the typefaces is a bit more organic with it's corners, shapes, and weights.

I think we can tweak the colors after the logo itself is done. (I'm partial to orange, magenta, or yet another blue)

**Comment by isaacdurazo** [comment]
Alright guys, I have a few color options. Also, @MichaelArestad I see what you are saying and you are right. After looking at other fonts, I found one that works way better than the one before.

Here three more color options:
![screen shot 2015-02-06 at 2 08 53 pm](https://cloud.githubusercontent.com/assets/1379244/6087525/d54a3ca6-ae09-11e4-8680-269ec4f724cd.png)

Just FYI, once we all agree on the logo, font and color, the next step will be to find complementary colors and present some possible scenarios of how to use them.

**Comment by sfrisk** [comment]
Those are nice!   I really like them.  And that font really pops with the
logo.

On Fri, Feb 6, 2015 at 4:11 PM, Isaac Durazo <notifications@github.com>
wrote:

> Alright guys, I have a few color options. Also, @MichaelArestad
> <https://github.com/MichaelArestad> I see what you are saying and you are
> right. After looking at other fonts, I found one that works way better than
> the one before.
>
> Here three more color options:
> [image: screen shot 2015-02-06 at 2 08 53 pm]
> <https://cloud.githubusercontent.com/assets/1379244/6087525/d54a3ca6-ae09-11e4-8680-269ec4f724cd.png>
>
> Just FYI, once we all agree on the logo, font and color, the next step
> will be to find complementary colors and present some possible scenarios of
> how to use them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/css-chassis/issues/27#issuecomment-73313133>.
>



-- 
Sarah Frisk
sarahfrisk.com

Twitter: twitter.com/SarahFrisk
LinkedIn: linkedin.com/in/sarahfrisk
Github: github.com/sfrisk

**Comment by arschmitz** [comment]
@isaacdurazo I really like that the font change is nice i really like those the C in chassis and the logo c are vary similar now. Im pretty torn on color...

**Comment by sfrisk** [comment]
I'm a fan of the pink and the blue one.

On Fri, Feb 6, 2015 at 4:14 PM, Alexander Schmitz <notifications@github.com>
wrote:

> @isaacdurazo <https://github.com/isaacdurazo> I really like that the font
> change is nice i really like those the C in chassis and the logo c are vary
> similar now. Im pretty torn on color...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/css-chassis/issues/27#issuecomment-73313671>.
>



-- 
Sarah Frisk
sarahfrisk.com

Twitter: twitter.com/SarahFrisk
LinkedIn: linkedin.com/in/sarahfrisk
Github: github.com/sfrisk

**Comment by MichaelArestad** [comment]
> I'm a fan of the pink and the blue one.

+ 1

**Comment by isaacdurazo** [comment]
Do you guys want to share this with more people to pick a winner? I'm still a fan of the green one, but I'm also happy with any other of the options, that's just my personal favorite.

**Comment by sfrisk** [comment]
I could bring it up again in the meeting today, see if more people have an opinion.

**Comment by geekman-rohit** [comment]
If followers of the project can share their opinion, The blue one :+1:

**Comment by arschmitz** [comment]
> I'm a fan of the pink and the blue one.

:+1:

**Comment by battaglr** [comment]
Great logo, @isaacdurazo!

:+1: to the "blue" one. But all are great.

**Comment by arschmitz** [comment]
Hmm... Looking at the blue one it looks really close to the jQuery core secondary blue http://brand.jquery.org/colors/#jquery-blue

**Comment by battaglr** [comment]
@arschmitz: that's something we should try to avoid?

**Comment by scottgonzalez** [comment]
I would not let that limit you.

**Comment by arschmitz** [comment]
Well this is a jQuery foundation project so its probably best to avoid the same colors as another foundation project logo, so the logos will often appear near each other. Also while this is a "jQuery Foundation" project it is not a "jQuery" project and we don't want to give that impression.

**Comment by isaacdurazo** [comment]
I don't think we should avoid using some colors. That would limit us incredibly. All the multiple jQuery projects use a lot of different colors and unless we are using an existing combination of colors and wouldn't worry. A color by itself is not a big deal.

**Comment by scottgonzalez** [comment]
> Well this is a jQuery foundation project so its probably best to avoid the same colors as another foundation project logo

Do you think the hundreds of Apache Software Foundation projects try to do this? This would become complete insanity very quickly.

> so the logos will often appear near each other.

Logos of similar color often appear next to each other.

**Comment by MichaelArestad** [comment]
I think the color similarity is a non issue.

**Comment by arschmitz** [comment]
Good points. I agree.

**Comment by sfrisk** [comment]
I like the blue one the most, followed by the pink.

On Tue, Feb 24, 2015 at 12:55 PM, Alexander Schmitz <
notifications@github.com> wrote:

> Good points. I agree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/css-chassis/issues/27#issuecomment-75809180>.
>



-- 
Sarah Frisk
sarahfrisk.com

Twitter: twitter.com/SarahFrisk
LinkedIn: linkedin.com/in/sarahfrisk
Github: github.com/sfrisk

**Comment by arthurvr** [comment]
> I like the blue one the most, followed by the pink.

+1 here.

**Comment by sfrisk** [comment]
Looks like between this issue thread and the IRC meeting channel, blue won.

**Comment by isaacdurazo** [comment]
Hey guys, sorry it took me so long to come up with this. Here are some situations in which the logo could  be presented and some complementary colors that can be used.

![screen shot 2015-04-07 at 2 06 18 pm](https://cloud.githubusercontent.com/assets/1379244/7033527/6ba691f0-dd2f-11e4-9ac4-276f98b7fac4.png)

![screen shot 2015-04-07 at 2 06 04 pm](https://cloud.githubusercontent.com/assets/1379244/7033531/6f3447d6-dd2f-11e4-9bff-1cde2c5aef08.png)

And for the stickers, I was thinking that maybe we could do something like this:
![screen shot 2015-04-07 at 2 09 44 pm](https://cloud.githubusercontent.com/assets/1379244/7033639/5f774126-dd30-11e4-8981-b09b2cd749aa.png)

What do you guys think?

**Comment by arschmitz** [comment]
@isaacdurazo Really liking the usages there gray background with color logo and dark text is my favorite :-)

**Comment by GreatDanton** [comment]
Dark logos are awesome. I like it.

**Comment by sfrisk** [comment]
Nice! I really like the theme!

**Comment by isaacdurazo** [comment]
Thanks guys, keep in mind that this are use cases. There're multiple scenarios in which a logo could be presented and we need to prepare for that.

**Comment by arschmitz** [comment]
@isaacdurazo absolutely i was just saying that was my favorite of them.

**Comment by arthurvr** [comment]
Awesome work @isaacdurazo! Looking really good! :+1: :trophy:

**Comment by cbracco** [comment]
This looks great, @isaacdurazo! The blue and dark-gray backgrounds with all-white logos feel like winners to me. I also really like the yellow accent color. :+1:

**Comment by MichaelArestad** [comment]
Boom! Looks great.

**Comment by ramasilveyra** [comment]
@isaacdurazo All the logos are pretty nice, thanks!

**Comment by geekman-rohit** [comment]
Simply Awesome. Period. :+1:

**Comment by isaacdurazo** [comment]
Thank you guys, I'm glad you like it. @sfrisk @arschmitz could you advice on next steps? do you want me to make a PR with the files?

**Comment by kborchers** [comment]
@isaacdurazo I would say let's not store those files in the repo. Maybe send them to @sfrisk and myself then I'll store them with all of our other assets and Sarah can distribute as she sees fit.

**Comment by sfrisk** [comment]
@kborchers @isaacdurazo sounds good to me.  Also if you have a SVG version of the logo, that would be cool.  I know @MichaelArestad and I discussed doing some fun animations with the logo.

**Comment by isaacdurazo** [comment]
Sounds like a plan! I'll get everything ready and send them later this afternoon

**Comment by sfrisk** [comment]
Awesome, thanks.

**Comment by kborchers** [comment]
Did this ever get wrapped up? If so, can someone send me the files and close this? Thanks!

**Comment by isaacdurazo** [comment]
@kristoferjoseph Yeah, I sent the files to @sfrisk. I'll send them to you as well.
