### ISSUE TITLE
CSS Framework or UI Toolkit?

### ISSUE THREAD

**Issue by yodasw16** [jquery/css-chassis#38]
Is this a CSS Framework or a UI Toolkit? After seeing Harry Roberts talk on the topic, I notice more and more that most people who are making "frameworks" are really making UI Toolkits. From what I've heard of Chassis, it seems like it will have a design and make a lot of decisions for icons, etc. Are those going to be things that are part of a theming system outside of the framework, or is that stuff part of the "framework"? If it's part of, UI Toolkit is probably a better definition of what this is.

Here's Harry's talk for reference: http://vimeo.com/95734680, https://speakerdeck.com/csswizardry/what-is-a-css-framework-anyway

**Comment by sfrisk** [comment]
Phase one of this project is definite more on the CSS framework side of things.  Just the stuff you need to get started on a project, with some useful helper classes.

Phase two is more adding the "UI Toolkit" side of things - which will be much more focused on being more of a super customizable theme.  Our goal is to make it easy for people to choose what they want to use.  If they just need the barebones 'CSS Framework' side of things to get started, then fine, they can download just the barebones.  If they want more UI components, then that is there too.

So I guess the answer is both? But the both part is more in the future.

**Comment by yodasw16** [comment]
Ok, that makes sense. I'm excited to start seeing some code for this project.
