### ISSUE TITLE
Is there some sort of roadmap?

### ISSUE THREAD

**Issue by battaglr** [jquery/css-chassis#39]
In the readme the goals of the project are really clear, but I was wondering if there is some sort of —public— roadmap for the project, or a public Trello or whatever helps to interested external collaborators to keep track of what's going on.

Thanks! And kudos for the great idea.

**Comment by arschmitz** [comment]
@battaglr There is not yet a roadmap, we will be working on one soon however I think. In a very general sense we are shooting for V1 mid year.

For public communication, we use issues, meeting notes ( http://meetings.jquery.org/category/chassis/ ), weekly meetings ( 1pm tuesdays in #jquery-meeting on freenode ), and IRC ( #css-chassis on freenode ). All of these are public, and any one is invited to participate. For tracking progress the best methods would be to watch the repo and follow the weekly meetings.

@battaglr Hope that helps

**Comment by battaglr** [comment]
@arschmitz: great! Thanks for the info. Just one thing, the weekly meetings are at 1 pm but in which time zone?

PS: feel free to close the issue if you consider it necessary; you've already answered my question.

**Comment by arschmitz** [comment]
@battaglr Sorry about that! 1PM EST. I'm actually going to leave it open because we don't have a road map right now, and its something I think we should have.

**Comment by battaglr** [comment]
@arschmitz: great, thanks!

**Comment by sfrisk** [comment]
Basic roadmap posted here, shall get more detailed in the future: 

https://github.com/jquery/css-chassis/wiki/Chassis-Roadmap
