### ISSUE TITLE
Consider using Gulp

### ISSUE THREAD

**Issue by battaglr** [jquery/css-chassis#40]
IMHO Gulp has some neat advantages over Grunt –which is also great.

- You are programing in JavaScript, not editing a JSON file. That brings a lot of flexibility to create custom tasks or whatever we can imagine without the need of a plugin.
- It's easier to understand/maintain —at least for me.
- It's –arguably– faster.
- The community is growing really fast —although Grunt's community is currently larger.

Finally, regardless the features of each one, the real question is: do we prefer code over configuration or configuration over code? If we answer that, further discussion is almost unnecessary.

*The fact that we are already using a build system or task manager is a good thing*.

**Comment by sfrisk** [comment]
The reason why we chose Grunt over Gulp is because Grunt is what is currently used on other foundation projects so its what most contributors are more familiar with, and also because Grunt provided us with the performance testing tools we needed.

**Comment by arschmitz** [comment]
We also plan to use https://github.com/gnarf/node-web-git-proxy, for easy branch preview builds, and our current setup there wants a grunt task for build.

**Comment by battaglr** [comment]
Fair enough. What you both said makes sense for me. Anyhow this could be one of those things to *reconsider* in the future.

**Comment by arschmitz** [comment]
@battaglr Absolutely, on a project like this no decision is ever final.

**Comment by jzaefferer** [comment]
Maybe one day someone writes a build tool that doesn't just promise optimized rebuilds based on timestamps like Make (or grunt-newer), but actually implements it all the way through tools like sass or various transpilers (maybe based on source maps). That kind of tool might make a real difference in performance.

**Comment by gnarf** [comment]
Yeah - also it's not that hard to change the build script for the `web-git-proxy` our current version already does checks for `Makefile` and `Gruntfile.js` -- https://github.com/jquery/infrastructure/blob/puppet-master/manifests/nodes/view.pp#L14 (for anyone with access)

```bash
#!/bin/bash -x
{
  set -e
  if test -f package.json ; then
    npm --no-color prune
    npm --no-color install
    npm --no-color update
  fi
  if test -f grunt.js ; then
    grunt --no-color --gruntfile grunt.js
  elif test -f Gruntfile.js ; then
    grunt --no-color --gruntfile Gruntfile.js
  elif test -f Makefile ; then
    make
  elif test -f build/Makefile ; then
    cd build
    make
  fi
} > build.out.txt 2>&1
```

it would be nothing to add a gulp check here
