### ISSUE TITLE
Create Semantic Color Variable Names

### ISSUE THREAD

**Issue by sfrisk** [jquery/css-chassis#43]
Add to the _colors.scss files the variable names for the base colors we'll be using.  

*Updated 04/07/2015*

This is by no means a final list, but should cover the base cases in the beginning, prior to having a more extensive style guide in place.  

    $color-font
    $color-link
    $color-button 
    $color-success
    $color-error
    $color-warning
    $color-background

I've included a list of active/focus/hover states as well for buttons and link, but if we have multiple buttons, it might be easier to have a mixin that tweaks focus/active/hover state colors based on original button color.  That makes it easier to deal with multiple states of different colored buttons.

    $color-link-focus
    $color-link-active
    $color-link-hover
    $color-button-focus 
    $color-button-active
    $color-button-hover

**Comment by geekman-rohit** [comment]
We have more colors in most frameworks: like a primary-color, warning-color ?? especially if we are looking at buttons?

**Comment by trailofdad** [comment]
The variables can be broken up into function and descriptive variables. Heres a reference: http://sachagreif.com/sass-color-variables/

**Comment by samatdav** [comment]
I did a quick research and found two great sources about having great variable names:

1. "Choosing great variable names" 
thesassway.com/beginner/variable-naming
In a nutshell: 
$red is bad
$brand-color is good

2. Official styleguide for color
sass-lang.com/styleguide/color
In the "Usage" section there is a way how they call variables at sass-lang.org itself:
$color-shadow
$color-primary 
$color-accent 
$color-background 
$color-background-shade 
$color-background-invert 
$color-text 
$color-text-weak 
$color-text-strong 
$color-text-heading 
$color-text-invert 
$color-text-strong-invert 
$color-background 
$color-text-link 
$color-primary 
$color-text-link-visited 
$color-text-link-hover 
$color-border

As you can see at sass website it is simply "color-" + element. In the first link it is element + "-color". I personally like any one as long as it is consistent. I believe it is important to find balance between descriptiveness and laconicism. For that reason I propose the following names for the variables ordered by my personal preference:

*default-font
⋅⋅*$color-text
⋅⋅*$text-color
⋅⋅*$color-text-default
⋅⋅*$text-default-color
*background
⋅⋅*$color-background
⋅⋅*$background-color
*default-button
⋅⋅*$color-button
⋅⋅*$button-color
⋅⋅*$color-default-button
⋅⋅*$default-button-color
*success
⋅⋅*$color-success
⋅⋅*$success-color
*error
⋅⋅*$color-error
⋅⋅*$error-color
*link
⋅⋅*$color-link
⋅⋅*$link-color

**Comment by samatdav** [comment]
I did a quick research and found two great sources about having great variable names:

1. "Choosing great variable names" 
thesassway.com/beginner/variable-naming
In a nutshell: 
$red is bad
$brand-color is good

2. Official styleguide for color
sass-lang.com/styleguide/color
In the "Usage" section there is a way how they call variables at sass-lang.org itself:
$color-shadow
$color-primary 
$color-accent 
$color-background 
$color-background-shade 
$color-background-invert 
$color-text 
$color-text-weak 
$color-text-strong 
$color-text-heading 
$color-text-invert 
$color-text-strong-invert 
$color-background 
$color-text-link 
$color-primary 
$color-text-link-visited 
$color-text-link-hover 
$color-border

As you can see at sass website it is simply "color-" + element. In the first link it is element + "-color". I personally like any one as long as it is consistent. I believe it is important to find balance between descriptiveness and laconicism. For that reason I propose the following names for the variables ordered by my personal preference:

* default-font
 $color-text
 $text-color
 $color-text-default
 $text-default-color

* background
 $color-background
 $background-color

* default-button
 $color-button
 $button-color
 $color-default-button
 $default-button-color

* success
 $color-success
 $success-color

* error
..* $color-error
 $error-color

* link
 $color-link
 $link-color

**Comment by trailofdad** [comment]
This is based on what is used in the SASS port for bootstrap and I find that it's very easy to use, and includes only whats necessary. It includes a scale of grays, and some default colors. Obviously the values would be different but I like the way they modify the grays from the base.

## >> Gray and colors for use across Chassis.

$gray-base:              #000
$gray-darker:            lighten($gray-base, 13.5%) // #222
$gray-dark:               lighten($gray-base, 20%)   // #333
$gray:                       lighten($gray-base, 33.5%) // #555
$gray-light:               lighten($gray-base, 46.7%) // #777
$gray-lighter:            lighten($gray-base, 93.5%) // #eee

$chassis-primary:         darken(#428bca, 6.5%) // #337ab7
$chassis-success:        #5cb85c
$chassis-info:               #5bc0de
$chassis-warning:        #f0ad4e
$chassis-danger:         #d9534f


## >> Chassis

### Settings for some of the most global styles.

** Background color for `<body>`.
$body-bg:               #fff
** Global text color on `<body>`.
$text-color:            $gray-dark

** Global textual link color.
$link-color:            $chassis-primary
** Link hover color set via `darken()` function.
$link-hover-color:      darken($link-color, 15%)
** Link hover decoration.
$link-hover-decoration: underline

**Comment by sfrisk** [comment]
Updated the description of this issue with a clearer list of color variables to include.

**Comment by laras126** [comment]
I think I can help with this - any status updates? I'll work in _colors.scss on master unless there is anything else to know.

**Comment by sfrisk** [comment]
We are actually in the middle of reviewing a PR to handle this.
