### ISSUE TITLE
Setup view.css-chassis.com

### ISSUE THREAD

**Issue by arschmitz** [jquery/css-chassis#58]
This will allow easy branch previews of built files

**Comment by akashnimare** [comment]
Hello 
I would like to contribute to this project via GSoC this year.  I would love to work on the Chassis website, adding demos, tutorials, and API documentation
Is there a mentor who can I discuss it with?

**Comment by arschmitz** [comment]
@akashnimare please go to #css-chassis on freenode and we will be happy to help you

**Comment by akashnimare** [comment]
Sure sir

**Comment by arschmitz** [comment]
All done http://view.css-chassis.com
