### ISSUE TITLE
Base styling for  <meter>

### ISSUE THREAD

**Issue by Noufal21** [jquery/css-chassis#71]
Issue in progress..

Update by sfrisk:
This issue covers the base styling for the `<meter>` element.  

Details on the`<meter>` element can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter)

**Comment by sfrisk** [comment]
Updated issue to include a description.  Also as a heads up,  `<meter>` is not currently supported in IE, Android, or Safari Mobile.  As stated in the meeting, there is an JS progress bar solution that  jQuery UI uses.

**Comment by sfrisk** [comment]
Closing this since it's covered in #80
