### ISSUE TITLE
Web Components Support

### ISSUE THREAD

**Issue by derekshull** [jquery/css-chassis#82]
Since chassis is wanting to push standards and be modular, would it make sense to create web components using HTML, CSS, and Javascript? Then no framework is needed, just a polyfill for the browsers that don't natively support custom elements, templates, shadow DOM, and/or HTML imports.

Better to start with it from the beginning than down the road. Web components have a promising future since they are created using the basic building blocks of the web rather than a framework.

**Comment by arschmitz** [comment]
@derekshull Hi thank you for the suggestion however this would not work for Chassis.

First chassis is a _CSS ONLY_ framework we will never distribute any sort of JavaScript. Our goal is to leave the JavaScript to javascript frameworks like Dojo, jQuery UI, jQuery Mobile etc. 

The second issue is support while polyfills like webcomponents.js exist they do not support all of the browsers which we support https://github.com/WebComponents/webcomponentsjs#browser-support Notice IE is only fully supported starting in version 11+ ( we support 8+ ), iOS only in version 7+ ( we support 5.1+ ), Android native browsers is not even listed at all ( and we support back to 2.3 ). 

@derekshull So while we thank you for looking into chassis and for the suggestion webcomponents are just not something that fit in with our goals for chassis.
