### ISSUE TITLE
Update Chassis to support node 0.12

### ISSUE THREAD

**Issue by sfrisk** [jquery/css-chassis#95]
Chassis should be testing and supporting node 0.10 and node 0.12.

**Comment by arthurvr** [comment]
Updating the Travis configuration and bumping dependencies should do it. If nobody argues against this I'm gonna do a PR.

**Comment by sfrisk** [comment]
Go for it!

**Comment by geekman-rohit** [comment]
:+1:  yay!

**Comment by sfrisk** [comment]
Update this to be supporting Node 4.
